#!/bin/ash
set -e
psql -v ON_ERROR_STOP --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    INSERT INTO "Cards"."CardData" ("SetId", "FrontAsset", "Name", "Cost", "Inkwell", "Classifications", "Ink", "Text", "CardType") VALUES        
    ('141', 'Cards/001', 'Belle', 3, true, '{ Dreamborn, Hero, Princess, Inventor }', 'Sapphire', 'Tinker: Whenever this character quests, you pay 1 {ink} less for the next item you play this turn.', 'Character'),
    ('174', 'Cards/002', 'Captain Hook', 1, true, '{ Dreamborn, Villain, Pirate, Captain }', 'Steel', '{Challenger} +2', 'Character'),
    ('72', 'Cards/003', 'Cruella De Vil', 2, true, '{ Storyborn, Villain }', 'Emerald', 'You''ll be sorry: When this character is challenged and banished, you may return chosen character to their player''s hand.', 'Character'),
    ('41', 'Cards/004', 'Elsa', 3, true, '{ Dreamborn, Hero, Queen, Sorcerer }', 'Amethyst', 'Freeze: [{Exert}] - Exert chosen opposing character.', 'Character'),
    ('181', 'Cards/005', 'Hercules', 3, true, '{ Dreamborn, Hero, Prince }', 'Steel', '{Bodyguard}', 'Character'),
    ('8', 'Cards/006', 'Lefou', 2, true, '{ Storyborn, Ally }', 'Amber', 'Loyal: If you have a character named Gaston in play, you pay 1 {ink} less to play this character.', 'Character'),
    ('113', 'Cards/007', 'Maleficent', 9, true, '{ Storyborn, Villain, Dragon }', 'Ruby', 'Dragon Fire: When you play this character, you may banish chosen opposing character.', 'Character'),
    ('115', 'Cards/008', 'Mickey Mouse', 8, true, '{ Dreamborn, Hero }', 'Ruby', '{Evasive}', 'Character'),
    ('157', 'Cards/009', 'Robin Hood', 6, true, '{ Storyborn, Hero }', 'Sapphire', 'Feed the poor: When you play this character, if an opponent has more cards in their hand than you, draw a card. / Good shot: During your turn, this character has Evasive.', 'Character'),
    ('23', 'Cards/010', 'Stitch', 6, true, '{ Floodborn, Hero, Alien }', 'Amber', ' Adoring fans: Whenever you play a character with a cost of 2 or less, you may exert it to draw a card.', 'Character'),
    ('130', 'Cards/011', 'Dragon Fire', 5, false, '{ Action }', 'Ruby', 'Banish chosen character', 'Action'),
    ('197', 'Cards/012', 'Fire The Cannons!', 1, false, '{ Action }', 'Steel', 'Deal 2 damage to chosen character', 'Action'),
    ('164', 'Cards/013', 'One Jump Ahead', 2, false, '{ Action, Song }', 'Sapphire', 'Put the top card of your deck into your ell facedown and exerted.', 'Action'),
    ('202', 'Cards/014', 'Frying Pan', 2, true, '{ Item }', 'Steel', 'Clang!: [Banish this item] - Chosen character can''t challenge during their next turn.', 'Item'),
    ('22', 'Cards/015', 'Stitch', 1, true, '{ Storyborn, Hero, Alien }', 'Amber', '', 'Character'),
    ('140', 'Cards/016', 'Aurora', 2, true, '{ Storyborn, Hero, Princess }', 'Sapphire', '', 'Character'),
    ('139', 'Cards/017', 'Aurora', 5, true, '{ Floodborn, Hero, Princess }', 'Sapphire', 'Protective Embrace: Your other characters gain {Ward}.', 'Character'),
    ('66', 'Cards/018', 'Magic Mirror', 2, false, '{ Item }', 'Amethyst', 'Speak!: [{Exert}, 4 {ink}] - Draw a card.', 'Item'),
    ('68', 'Cards/019', 'White Rabbit''s Pocket Watch', 3, true, '{ Item }', 'Amethyst', 'I''m Late!: [{Exert}, 1 {ink}] - Chosen character gains {Rush}.', 'Item'),
    ('47', 'Cards/020', 'Magic Broom', 2, true, '{ Dreamborn, Broom }', 'Amethyst', 'Sweep: When you play this character, you may shuffle a card from any discard into its player''s deck.', 'Character'),
    ('51', 'Cards/021', 'Mickey Mouse', 4, true, '{ Dreamborn, Sorcerer }', 'Amethyst', 'Animate Broom: You play 1 {ink} less to play Broom characters. / Ceaseless Worker: Whenever one of your Broom characters is banished in a challenge, you may return that card to your hand.', 'Character'),
    ('6', 'Cards/022', 'Hades', 4, false, '{ Storyborn, Villain, Deity }', 'Amber', 'Well of Souls: When you play this character, return a character from your discard pile to your hand.', 'Character'),
    ('163', 'Cards/023', 'Let It Go', 5, true, '{ Action, Song }', 'Sapphire', 'Put chosen character into their player''s inkwell facedown and exerted.', 'Action'),
    ('14', 'Cards/024', 'Moana', 5, true, '{ Storyborn, Hero, Princess }', 'Amber', 'We Can Fix It: Whenever this character quests, you may ready your other Princess characters. They can''t quest for the rest of the turn.', 'Character'),
    ('33', 'Cards/025', 'Lantern', 2, false, '{ Item }', 'Amber', 'Birthday Lights: [{Exert}] - You play 1 {ink} less for the next character you play this turn.', 'Item'),
    ('172', 'Cards/026', 'Beast', 5, true, '{ Storyborn, Hero, Prince }', 'Steel', 'Break: When you play this character, you may banish chosen item.', 'Character'),
    ('173', 'Cards/027', 'Captain Hook', 4, false, '{ Storyborn, Villain, Pirate, Captain }', 'Steel', 'Double the Powder!: When you play this character, you may return an action named Fire the Cannons! from your discard pile to your hand.', 'Character'),
    ('64', 'Cards/028', 'Friends On The Other Side', 3, true, '{ Action, Song }', 'Amethyst', 'Draw 2 cards', 'Action'),
    ('49', 'Cards/029', 'Maleficent', 3, true, '{ Storyborn, Villain, Sorcerer }', 'Amethyst', 'Cast my Spell!: When you play this character, you may draw a card.', 'Character'),
    ('25', 'Cards/030', 'Be Our Guest', 2, true, '{ Action, Song }', 'Amber', 'Look at the top 4 cards of your deck. You may reveal a character card and put it in your hand. Put the rest on the bottom of your deck in any order.', 'Action'),
    ('152', 'Cards/031', 'Maurice', 6, true, '{ Dreamborn, Mentor, Inventor }', 'Sapphire', 'Give it a try: Whenever this character quests, you pay 2 {ink} less for the next item you play this turn. / It Works: Whenever you play an item, you may draw a card.', 'Character'),
    ('122', 'Cards/032', 'Scar', 4, true, '{ Dreamborn, Villain }', 'Ruby', '', 'Character'),
    ('138', 'Cards/033', 'Aurora', 4, true, '{ Storyborn, Hero, Princess }', 'Sapphire', 'Disarming Beauty: When you play this character, chosen opposing character gets -2 {strength} this turn.', 'Character'),
    ('108', 'Cards/034', 'Donald Duck', 2, true, '{ Storyborn }', 'Ruby', '', 'Character'),
    ('13', 'Cards/035', 'Minnie Mouse', 2, true, '{ Dreamborn, Princess }', 'Amber', '', 'Character'),
    ('158', 'Cards/036', 'Scar', 6, true, '{ Storyborn, Villain }', 'Sapphire', 'Insidious Plot: When you play this character, chosen opposing character gets -5 {strength} this turn.', 'Character'),
    ('104', 'Cards/037', 'Aladdin', 7, true, '{ Floodborn, Hero }', 'Ruby', 'Daring Exploit: During your turn, whenever this character banishes another character in a challenge, you gain 2 lore and each opponent loses 2 lore.', 'Character'),
    ('118', 'Cards/038', 'Mulan', 5, true, '{ Storyborn, Hero, Princess }', 'Ruby', 'Lead by Example: During your turn whenever this character banishes another characters in a challenge, your other characters get +1 {lore} this turn.', 'Character'),
    ('154', 'Cards/039', 'Mickey Mouse', 3, false, '{ Dreamborn, Hero, Detective }', 'Sapphire', 'Get a Clue: When you play this character, you may put the top card of your deck into your inkwell facedown and exerted.', 'Character'),
    ('186', 'Cards/040', 'Mickey Mouse', 6, true, '{ Dreamborn, Hero, Musketeer }', 'Steel', '{Bodyguard} / All for One: Your other Musketeer characters get +1 {strength}.', 'Character'),
    ('200', 'Cards/041', 'Smash', 3, true, '{ Action }', 'Steel', 'Deal 3 damage to the chosen character', 'Action'),
    ('7', 'Cards/042', 'Heihei', 1, true, '{ Storyborn, Ally }', 'Amber', '{Support}', 'Character'),
    ('201', 'Cards/043', 'Beast''s Mirror', 2, true, '{ Item }', 'Steel', 'Show Me: [{Exert}, 3 {ink}] - If you have no cards in your hand, draw a card.', 'Item'),
    ('53', 'Cards/044', 'Pascal', 1, true, '{ Storyborn, Ally }', 'Amethyst', 'Camouflage: While you have another character in play, this character gains {Evasive}.', 'Character'),
    ('71', 'Cards/045', 'Cheshire Cat', 3, true, '{ Storyborn }', 'Emerald', 'Lose Something?: When this character is challenged and banished, banish the challenging character', 'Character'),
    ('99', 'Cards/046', 'The Beast Is Mine!', 3, true, '{ Action }', 'Emerald', 'Chosen character gains {Reckless} during their next turn.', 'Action'),
    ('189', 'Cards/047', 'Simba', 7, true, '{ Storyborn, Hero, King }', 'Steel', '{Challenger} +4 / Pounce: During your turn, this character gains {Evasive}.', 'Character'),
    ('148', 'Cards/048', 'Jasmine', 3, true, '{ Storyborn, Princess }', 'Sapphire', '', 'Character'),
    ('187', 'Cards/049', 'Prince Eric', 2, true, '{ Storyborn, Prince, Hero }', 'Steel', '{Challenger} +2', 'Character'),
    ('179', 'Cards/050', 'Goons', 1, true, '{ Storyborn, Ally }', 'Steel', '', 'Character'),
    ('45', 'Cards/051', 'Jafar', 4, true, '{ Dreamborn, Villain, Sorcerer }', 'Amethyst', '{Challenger} +3', 'Character'),
    ('38', 'Cards/052', 'Dr. Facilier', 2, true, '{ Storyborn, Villain, Sorcerer }', 'Amethyst', '{Challenger} +2', 'Character'),
    ('11', 'Cards/053', 'Maximus', 3, true, '{ Dreamborn, Ally }', 'Amber', 'Horsekick: When you play this character, chosen character gets -2 {strength} this turn.', 'Character'),
    ('1', 'Cards/054', 'Ariel', 4, true, '{ Storyborn, Hero, Princess }', 'Amber', 'Voiceless: This character can''t {Exert} to sing songs.', 'Character'),
    ('57', 'Cards/055', 'The Wardrobe', 3, true, '{ Dreamborn, Ally }', 'Amethyst', '', 'Character'),
    ('150', 'Cards/056', 'Maleficent', 4, true, '{ Storyborn, Villain, Sorcerer }', 'Sapphire', '', 'Character'),
    ('83', 'Cards/057', 'Jumba Jookiba', 5, true, '{ Dreamborn, Alien, Inventor }', 'Emerald', '', 'Character'),
    ('89', 'Cards/058', 'Mickey Mouse', 3, true, '{ Storyborn, Hero, Captain }', 'Emerald', '', 'Character'),
    ('12', 'Cards/059', 'Mickey Mouse', 3, true, '{ Storyborn, Hero }', 'Amber', '', 'Character'),
    ('48', 'Cards/060', 'Maleficent', 1, false, '{ Dreamborn, Villain, Sorcerer }', 'Amethyst', '', 'Character'),
    ('60', 'Cards/061', 'Yzma', 2, true, '{ Dreamborn, Villain, Sorcerer }', 'Amethyst', 'You''re Excused: Whenever this character quests, looks at the top card of your deck. Put it either on the top or bottom of your deck.', 'Character'),
    ('26', 'Cards/062', 'Control Your Temper', 1, true, '{ Action }', 'Amber', 'Chosen character gets -2 {strength} this turn.', 'Action'),
    ('29', 'Cards/063', 'Just In Time', 3, false, '{ Action }', 'Amber', 'You may play a character with cost 5 or less for free.', 'Action'),
    ('161', 'Cards/064', 'Develop Your Brain', 1, true, '{ Action }', 'Sapphire', 'Look at the top 2 cards of your deck. Put one into your hand and the other on the bottom of the deck.', 'Action'),
    ('166', 'Cards/065', 'Coconut Basket', 2, true, '{ Item }', 'Sapphire', 'Consider The Coconut: Whenever you play a character, you may remove up to 2 damage from chosen character.', 'Item'),
    ('30', 'Cards/066', 'Part Of Your World', 3, false, '{ Action, Song }', 'Amber', 'Return a character card from your discard to your hand.', 'Action'),
    ('145', 'Cards/067', 'Flounder', 1, true, '{ Storyborn, Ally }', 'Sapphire', '', 'Character'),
    ('32', 'Cards/068', 'Dinglehopper', 1, true, '{ Item }', 'Amber', 'Straighten Hair: [{Exert}] - Remove up to 1 damage from chosen character.', 'Item'),
    ('28', 'Cards/069', 'Healing Glow', 1, true, '{ Action }', 'Amber', 'Remove up to 2 damage from chosen character.', 'Action'),
    ('194', 'Cards/070', 'Tinker Bell', 3, true, '{ Dreamborn, Ally, Fairy }', 'Steel', 'Battle Plans: [{Exert}] - Draw a card, then choose and discard a card.', 'Character'),
    ('178', 'Cards/071', 'Gantu', 8, true, '{ Storyborn, Alien, Captain }', 'Steel', 'Under Arrest: Characters with cost 2 or less can''t challenge your character.', 'Character'),
    ('5', 'Cards/072', 'Hades', 8, false, '{ Floodborn, Villain, King, Deity }', 'Amber', 'Sinister Plot: This character gets +1 {lore} for each other Villain character you have in play.', 'Character'),
    ('52', 'Cards/073', 'Olaf', 1, true, '{ Storyborn, Ally }', 'Amethyst', '', 'Character'),
    ('75', 'Cards/074', 'Genie', 6, false, '{ Storyborn, Ally }', 'Emerald', '{Evasive} / Disappear: When you play this character, you may return chosen character to the player''s hand.', 'Character'),
    ('80', 'Cards/075', 'Iago', 3, true, '{ Storyborn, Ally }', 'Emerald', 'You got a problem?: [{Exert}] - Chosen character gains {Reckless} during their next turn.', 'Character'),
    ('24', 'Cards/076', 'Timon', 1, true, '{ Storyborn, Ally }', 'Amber', 'Tastes Lke Chicken: When you play this character, you may remove up to 1 damage from chosen character.', 'Character'),
    ('36', 'Cards/077', 'Archimedes', 1, true, '{ Dreamborn, Ally }', 'Amethyst', '', 'Character'),
    ('54', 'Cards/078', 'Rafiki', 3, false, '{ Dreamborn, Mentor, Sorcerer }', 'Amethyst', '{Rush}', 'Character'),
    ('70', 'Cards/079', 'Beast', 5, false, '{ Dreamborn, Hero, Prince }', 'Emerald', '{Rush} / Roar: When you play this character, exert all opposing damage characters.', 'Character'),
    ('69', 'Cards/080', 'Aladdin', 2, true, '{ Storyborn, Hero, Prince }', 'Emerald', '{Ward}', 'Character'),
    ('111', 'Cards/081', 'Goofy', 5, true, '{ Dreamborn, Hero }', 'Ruby', '{Evasive}', 'Character'),
    ('85', 'Cards/082', 'Lady Tremaine', 6, false, '{ Dreamborn, Villain }', 'Emerald', 'Do it again!: When you play this character, you may return an action card from your discard to your hand.', 'Character'),
    ('127', 'Cards/083', 'Tigger', 6, true, '{ Storyborn, Tigger }', 'Ruby', '{Evasive}', 'Character'),
    ('4', 'Cards/084', 'Goofy', 5, true, '{ Dreamborn, Hero, Musketeer }', 'Amber', '{Bodyguard}', 'Character'),
    ('121', 'Cards/085', 'Rapunzel', 6, false, '{ Dreamborn, Hero, Princess }', 'Ruby', 'Tangle: When you play this character, each opponent loses 1 lore.', 'Character'),
    ('21', 'Cards/086', 'Stitch', 7, true, '{ Dreamborn, Hero, Alien }', 'Amber', 'Ohana: When you play this character, if you have 2 or more other characters in play, you may draw 2 cards.', 'Character'),
    ('55', 'Cards/087', 'Sven', 6, true, '{ Storyborn, Ally }', 'Amethyst', '', 'Character'),
    ('185', 'Cards/088', 'Maui', 8, true, '{ Storyborn, Hero, Deity }', 'Steel', '', 'Character'),
    ('91', 'Cards/089', 'Peter Pan', 3, true, '{ Dreamborn, Hero }', 'Emerald', '{Evasive}', 'Character'),
    ('137', 'Cards/090', 'Ariel', 4, false, '{ Storyborn, Hero, Princess }', 'Sapphire', 'Look at this stuff: Whenever you play an item, you may ready this character.', 'Character'),
    ('61', 'Cards/091', 'Zeus', 4, false, '{ Storyborn, Deity }', 'Amethyst', '{Rush} / {Challenger} +4', 'Character'),
    ('188', 'Cards/092', 'Simba', 1, true, '{ Storyborn, Hero, Prince }', 'Steel', 'Guess what?: When you play this character, you may draw a card, then choose and discard a card.', 'Character'),
    ('144', 'Cards/093', 'Donald Duck', 5, true, '{ Dreamborn, Hero, Inventor }', 'Sapphire', '{Ward}', 'Character'),
    ('182', 'Cards/094', 'Kristoff', 3, true, '{ Storyborn, Ally }', 'Steel', '', 'Character'),
    ('153', 'Cards/095', 'Merlin', 4, true, '{ Dreamborn, Mentor, Sorcerer }', 'Sapphire', '{Support}', 'Character'),
    ('20', 'Cards/096', 'Simba', 2, true, '{ Storyborn, Hero, Prince }', 'Amber', '{Bodyguard}', 'Character'),
    ('193', 'Cards/097', 'Tinker Bell', 6, true, '{ Floodborn, Ally, Fairy }', 'Steel', 'Rock the Boat: When you play this character, deal 1 damage to each opposing character. / Puny Pirate: During your turn, whenever this character banishes another character in a challenge, you may deal 2 damage to chosen opposing character.', 'Character'),
    ('62', 'Cards/098', 'Befuddle', 1, true, '{ Action }', 'Amethyst', 'Return a character or item with cost 2 or less to their player''s hand.', 'Action'),
    ('183', 'Cards/099', 'Kronk', 6, true, '{ Storyborn, Ally }', 'Steel', '', 'Character'),
    ('120', 'Cards/100', 'Pongo', 4, true, '{ Storyborn, Hero }', 'Ruby', '{Evasive}', 'Character'),
    ('176', 'Cards/101', 'Cerberus', 5, true, '{ Storyborn }', 'Steel', '', 'Character'),
    ('9', 'Cards/102', 'Lilo', 1, false, '{ Storyborn, Hero }', 'Amber', '', 'Character'),
    ('43', 'Cards/103', 'Flotsam', 5, false, '{ Storyborn, Ally }', 'Amethyst', '{Rush} / Dexterous Lunge: Your characters named Jetsam gain {Rush}.', 'Character'),
    ('46', 'Cards/104', 'Jetsam', 4, true, '{ Storyborn, Ally }', 'Amethyst', '{Evasive} / Sinister Slither: Your characters named Flotsam gain {Evasive}.', 'Character'),
    ('160', 'Cards/105', 'Triton', 7, true, '{ Storyborn, King }', 'Sapphire', '', 'Character'),
    ('198', 'Cards/106', 'Grab Your Sword', 5, false, '{ Action, Song }', 'Steel', 'Deal 2 damage to each opposing character.', 'Action'),
    ('35', 'Cards/107', 'Anna', 4, true, '{ Storyborn, Hero, Queen }', 'Amethyst', 'Loving Heart: When you play this this character, if you have a characater named Elsa in play, choose an opposing character. The chosen character doesn''t ready at the start of their next turn.', 'Character'),
    ('2', 'Cards/108', 'Ariel', 3, true, '{ Storyborn, Hero, Princess }', 'Amber', '{Singer} 5 / Musical Debut: When you play this character, look at the top 4 cards of your deck. You may reveal a song card and put it into your hand. Put the rest on the bottom of your deck in any order.', 'Character'),
    ('124', 'Cards/109', 'Sergeant Tibbs', 1, true, '{ Storyborn, Ally }', 'Ruby', '', 'Character'),
    ('110', 'Cards/110', 'Gaston', 2, true, '{ Storyborn, Villain }', 'Ruby', '{Reckless}', 'Character'),
    ('19', 'Cards/111', 'Sebastian', 2, true, '{ Storyborn, Ally }', 'Amber', '{Singer} 4', 'Character'),
    ('34', 'Cards/112', 'Ursula''s Shell Necklace', 3, false, '{ Item }', 'Amber', 'Now, Sing!: Whenever you play a song, you may pay 1 {ink} to draw a card.', 'Item'),
    ('131', 'Cards/113', 'Fan The Flames', 1, true, '{ Action }', 'Ruby', 'Ready chosen character. They can''t quest for the rest of this turn.', 'Action'),
    ('162', 'Cards/114', 'If It''s Not Baroque', 3, false, '{ Action }', 'Sapphire', 'Return an item card from your discard to your hand.', 'Action'),
    ('196', 'Cards/115', 'Break', 2, true, '{ Action }', 'Steel', 'Banish chosen item.', 'Action'),
    ('16', 'Cards/116', 'Prince Phillip', 4, false, '{ Storyborn, Hero, Prince }', 'Amber', 'Heroism: When this character challenges and is banished, you may banish the challenged character.', 'Character'),
    ('105', 'Cards/117', 'Aladdin', 3, true, '{ Storyborn, Hero }', 'Ruby', 'Improvise: When you play this character, each opponent loses 1 lore.', 'Character'),
    ('151', 'Cards/118', 'Maleficent', 5, true, '{ Dreamborn, Villain, Sorcerer }', 'Sapphire', '', 'Character'),
    ('203', 'Cards/119', 'Musketeer Tabard', 4, false, '{ Item }', 'Steel', 'All for one and one for all: Whenever one of your characters with {Bodyguard} is banished, you may draw a card.', 'Item'),
    ('73', 'Cards/120', 'Duke Of Weselton', 1, true, '{ Storyborn, Villain }', 'Emerald', '', 'Character'),
    ('116', 'Cards/121', 'Minnie Mouse', 1, true, '{ Storyborn, Hero }', 'Ruby', '', 'Character'),
    ('170', 'Cards/122', 'Scepter of Arendelle', 1, true, '{ Item }', 'Sapphire', 'Command: [{Exert}] - Chosen character gains {Support} this turn.', 'Item'),
    ('78', 'Cards/123', 'Hans', 4, true, '{ Storyborn, Villain, Prince }', 'Emerald', '', 'Character'),
    ('96', 'Cards/124', 'Stampede', 1, false, '{ Action }', 'Emerald', 'Deal 2 damage to chosen damaged character.', 'Action'),
    ('50', 'Cards/125', 'Marshmallow', 6, false, '{ Storyborn, Ally }', 'Amethyst', 'Durable: When this character is banished in a challenge, you may return this card to your hand.', 'Character'),
    ('100', 'Cards/126', 'Vicious Betrayal', 1, true, '{ Action }', 'Emerald', 'Chosen character gets +2 {strength} this turn. If a Villain character is chosen, they get +3 {strength} instead.', 'Action'),
    ('128', 'Cards/127', 'Be Prepared', 7, false, '{ Action, Song }', 'Ruby', 'Banish all characters.', 'Action'),
    ('195', 'Cards/128', 'A Whole New World', 5, false, '{ Action, Song }', 'Steel', 'Each player discards their hand and draws 7 cards.', 'Action'),
    ('95', 'Cards/129', 'Mother Knows Best', 3, false, '{ Action, Song }', 'Emerald', 'Return chosen character to their player''s hand.', 'Action'),
    ('65', 'Cards/130', 'Reflection', 1, true, '{ Action, Song }', 'Amethyst', 'Look at the top 3 cards of your deck. Put them back on the top of your deck in any order.', 'Action'),
    ('27', 'Cards/131', 'Hakuna Matata', 4, true, '{ Action, Song }', 'Amber', 'Remove up to 3 damage from each of your characters.', 'Action'),
    ('88', 'Cards/132', 'Mickey Mouse', 7, false, '{ Floodborn, Hero }', 'Emerald', 'Misdirection: Whenever you play an action, chosen opposing character can''t quest during their next turn.', 'Character'),
    ('94', 'Cards/133', 'Do It Again', 3, false, '{ Action }', 'Emerald', 'Return an action card from your discard to your hand.', 'Action'),
    ('102', 'Cards/134', 'Stolen Scimitar', 3, true, '{ Item }', 'Emerald', 'Slash: [{Exert}] - Chosen characters gets +1 {strength} this turn. If a character named Aladdin is chosen, he gets +2 {strength} instead.', 'Item'),
    ('180', 'Cards/135', 'Hans', 4, true, '{ Storyborn, Villain, Prince }', 'Steel', 'Stage a Little Accident: Whenever this character quests, you may deal 1 damage to chosen character.', 'Character'),
    ('18', 'Cards/136', 'Rapunzel', 4, true, '{ Storyborn, Hero, Princess }', 'Amber', 'Gleam and Glow: When you play this character, remove up to 3 damage from one of your characters. Draw a card for each 1 damage removed this way.', 'Character'),
    ('74', 'Cards/137', 'Flynn Rider', 2, true, '{ Storyborn, Hero, Prince }', 'Emerald', 'Here comes the Smolder: Whenever this character is challenged, the challenging player chooses and discards a card.', 'Character'),
    ('10', 'Cards/138', 'Maximus', 5, true, '{ Storyborn, Ally }', 'Amber', '{Bodyguard} / {Support}', 'Character'),
    ('87', 'Cards/139', 'Megara', 2, true, '{ Dreamborn, Ally }', 'Emerald', 'Wonder Boy: When you play this character, chosen character gets +2 {strength} this turn.', 'Character'),
    ('40', 'Cards/140', 'Elsa', 4, true, '{ Storyborn, Hero, Queen, Sorcerer }', 'Amethyst', '', 'Character'),
    ('84', 'Cards/141', 'Kuzco', 5, false, '{ Storyborn, King }', 'Emerald', '{Ward} / No Touchy!: When this character is challenged and banished, you may banish the challenging character.', 'Character'),
    ('77', 'Cards/142', 'Geni', 2, true, '{ Dreamborn, Ally }', 'Emerald', '', 'Character'),
    ('103', 'Cards/143', 'Abu', 3, true, '{ Storyborn, Ally }', 'Ruby', '', 'Character'),
    ('123', 'Cards/144', 'Scar', 8, false, '{ Floodborn, Villain, King }', 'Ruby', 'Rousing Speech: When you play this character, ready your characters with cost 3 or less. They can''t quest for the rest of this turn.', 'Character'),
    ('82', 'Cards/145', 'John Silver', 6, true, '{ Storyborn, Villain, Alien, Pirate, Captain }', 'Emerald', 'Pick your Fights: When you play this character and whenever he quests, chosen opposing character gains {Reckless} during their next turn.', 'Character'),
    ('175', 'Cards/146', 'Captain Hook', 5, false, '{ Floodborn, Villain, Pirate, Captain }', 'Steel', '{Challenger} +3 / Stolen Dust: Characters with cost 3 or less can''t challenge this character.', 'Character'),
    ('81', 'Cards/147', 'Jasper', 3, true, '{ Storyborn, Ally }', 'Emerald', 'Puppynapping: Whenever this character quests, chosen opposing character can''t quest during thier next turn.', 'Character'),
    ('79', 'Cards/148', 'Horace', 4, true, '{ Storyborn, Ally }', 'Emerald', '', 'Character'),
    ('42', 'Cards/149', 'Elsa', 8, false, '{ Floodborn, Hero, Queen, Sorcerer }', 'Amethyst', 'Deep Freeze: When you play this character, exert up to 2 chosen characters. They can''t ready at the start of their next turn.', 'Character'),
    ('109', 'Cards/150', 'Elsa', 4, true, '{ Dreamborn, Hero, Queen, Sorcerer }', 'Ruby', 'That''s no  Blizzard: Whenever you play a character named Anna, ready this character. This character can''t quest for the rest of this turn.', 'Character'),
    ('58', 'Cards/151', 'Tinker Bell', 5, false, '{ Storyborn, Ally, Fairy }', 'Amethyst', '{Evasive} / Loyal and Devoted: Your characters named Peter Pan gain {Challenger} +1.', 'Character'),
    ('44', 'Cards/152', 'Jafar', 4, true, '{ Dreamborn, Villain, Sorcerer }', 'Amethyst', 'Hidden Wonders: This character gets +1 {strength} for each card in your hand.', 'Character'),
    ('134', 'Cards/153', 'Poisoned Apple', 3, false, '{ Item }', 'Ruby', 'Take a Bite: [1 {ink}, Banish this item] - Exert chosen character. If a Princess character is chosen, banish her instead.', 'Item'),
    ('67', 'Cards/154', 'Ursula''s Cauldron', 2, false, '{ Item }', 'Amethyst', 'Peer Into The Depths: [{Exert}] - Look at the top 2 cards of your deck. Put one on the top of your deck and the other on the bottom.', 'Item'),
    ('98', 'Cards/155', 'Sudden Chill', 2, true, '{ Action, Song }', 'Emerald', 'Each opponent chooses and discards a card.', 'Action'),
    ('112', 'Cards/156', 'Lefou', 2, true, '{ Dreamborn, Ally }', 'Ruby', 'Fan the Flames: When you play this character, ready chosen character. They can''t quest for the rest of this turn.', 'Character'),
    ('107', 'Cards/157', 'Captain Hook', 7, false, '{ Storyborn, Villain, Pirate, Captain }', 'Ruby', '{Rush} / You Coward!: While this character is exerted, opposing characters with {Evasive} gain {Reckless}.', 'Character'),
    ('129', 'Cards/158', 'Cut To The Chase', 2, true, '{ Action }', 'Ruby', 'Chosen character gains {Rush}.', 'Action'),
    ('133', 'Cards/159', 'Tangle', 2, true, '{ Action }', 'Ruby', 'Each opponent loses 1 lore.', 'Action'),
    ('132', 'Cards/160', 'He''s Got A Sword', 1, true, '{ Action }', 'Ruby', 'Chosen character gets +2 {strength} this turn.', 'Action'),
    ('136', 'Cards/161', 'Sword Of Truth', 4, false, '{ Item }', 'Ruby', 'Final Enchantment: [Banish this item] - Banish chosen Villain character.', 'Item'),
    ('142', 'Cards/162', 'Belle', 4, true, '{ Storyborn, Hero, Princess }', 'Sapphire', 'Read a Book: During your turn, you may put an additional card from your hand into your inkwell facedown. / My Favorite Part!: While you have 10 or more cards in your inkwell, this character gets +4 {lore}.', 'Character'),
    ('90', 'Cards/163', 'Mother Gothel', 6, true, '{ Storyborn, Villain }', 'Emerald', 'Skip the Drama, Stay with Mama: While this character is exerted, opposing characters can''t quest.', 'Character'),
    ('165', 'Cards/164', 'Work Together', 1, true, '{ Action }', 'Sapphire', 'Chosen character gains {Support} this turn.', 'Action'),
    ('149', 'Cards/165', 'Jasmine', 5, true, '{ Floodborn, Hero, Princess, Queen }', 'Sapphire', 'Caretaker: When you play this character and whenever she quests, you may remove up to 2 damage from each of your characters.', 'Character'),
    ('37', 'Cards/166', 'Dr. Facilier', 7, false, '{ Floodborn, Villain, Sorcerer }', 'Amethyst', 'Into the Shadows: Whenever one of your otehr characters is banashed in a challenge, you may return that card to your hand.', 'Character'),
    ('3', 'Cards/167', 'Cinderella', 4, true, '{ Storyborn, Hero, Princess }', 'Amber', '{Singer} 5 / A Wonderful Dream: [{Exert}] - Remove up to 3 damage from chosen Princess character.', 'Character'),
    ('86', 'Cards/168', 'Mad Hatter', 5, true, '{ Storyborn }', 'Emerald', 'Tea Party: Whenever this character is challenged, you may draw a card.', 'Character'),
    ('97', 'Cards/169', 'Steal From The Rich', 5, false, '{ Action }', 'Emerald', 'Whenever one of your characters quests this turn, each opponent loses 1 lore.', 'Character'),
    ('106', 'Cards/170', 'Captain', 5, true, '{ Storyborn, Ally, Captain }', 'Ruby', '', 'Character'),
    ('125', 'Cards/171', 'Stitch', 6, true, '{ Storyborn, Hero, Alien }', 'Ruby', '', 'Character'),
    ('135', 'Cards/172', 'Shield Of Virtue', 1, true, '{ Item }', 'Ruby', 'Fireproof: [{Exert}, 3 {ink}] - Ready chosen character. They can''t quest for the rest of the turn.', 'Item'),
    ('146', 'Cards/173', 'Gramma Tala', 2, true, '{ Storyborn, Mentor }', 'Sapphire', 'I Will Be With You: When this character is banished, you may put this card into your inkwell facedown and exerted.', 'Character'),
    ('155', 'Cards/174', 'Mufasa', 6, true, '{ Storyborn, Mentor, King }', 'Sapphire', '', 'Character'),
    ('169', 'Cards/175', 'Magic Golden Flower', 1, true, '{ Item }', 'Sapphire', 'Healing Pollen: [Banish this item] - Remove up to 3 damage from a chosen character.', 'Character'),
    ('190', 'Cards/176', 'Simba', 5, false, '{ Storyborn, Hero, Prince }', 'Steel', 'I know what I have to do: During your turn, whenever this character banishes another character in a challenge, you gain 1 lore.', 'Character'),
    ('199', 'Cards/177', 'Ransack', 2, true, '{ Action }', 'Steel', 'Draw 2 cards, then choose and discard 2 cards.', 'Character'),
    ('15', 'Cards/178', 'Mr. Smee', 3, true, '{ Dreamborn, Ally, Pirate }', 'Amber', '', 'Character'),
    ('17', 'Cards/179', 'Pumba', 4, true, '{ Storyborn, Ally }', 'Amber', '', 'Character'),
    ('31', 'Cards/180', 'You Have Forgotten Me', 4, true, '{ Action }', 'Amber', 'Each opponent chooses and discards 2 cards.', 'Action'),
    ('39', 'Cards/181', 'Dr. Facilier', 3, true, '{ Storyborn, Villain, Sorcerer }', 'Amethyst', 'Dreams Made Real: Whenever you play a song, you may look at the top 2 cards of your deck. Put one on the top of oyur deck and the other on the bottom.', 'Character'),
    ('56', 'Cards/182', 'The Queen', 5, true, '{ Storyborn, Villain, Queen }', 'Amethyst', 'I summon thee: [{Exert}] - Draw a card.', 'Character'),
    ('59', 'Cards/183', 'Ursula', 7, false, '{ Storyborn, Villain, Sorcerer }', 'Amethyst', 'It''s Too Easy: When you play this character, each opponent loses 1 lore. You may draw a card for each lore lost this way.', 'Character'),
    ('63', 'Cards/184', 'Freeze', 2, false, '{ Action }', 'Amethyst', 'Exert chosen character', 'Action'),
    ('76', 'Cards/185', 'Genie', 8, false, '{ Floodborn, Hero }', 'Emerald', '{Evasive} / Phenomenal Cosmic Power!: Whenever this character quests, you may play an action with cost 5 or less for free.', 'Character'),
    ('92', 'Cards/186', 'Tamatoa', 2, true, '{ Dreamborn }', 'Emerald', '', 'Character'),
    ('93', 'Cards/187', 'Tinker Bell', 4, true, '{ Storyborn, Ally, Fairy }', 'Emerald', '{Evasive} / Pixie Dust: When you play this character, chosen character gains {Evasive} this turn.', 'Character'),
    ('101', 'Cards/188', 'Dr. Facilier''s Cards', 2, false, '{ Item }', 'Emerald', 'The Cards Will Tell: [{Exert}] - You pay 1 {ink} less for the next action you play this turn', 'Item'),
    ('114', 'Cards/189', 'Maui', 5, true, '{ Storyborn, Hero, Deity }', 'Ruby', '{Rush} / {Reckless}', 'Character'),
    ('117', 'Cards/190', 'Moana', 5, true, '{ Storyborn, Hero, Princess }', 'Ruby', 'This is not who you are: When you play this character, you may banish chosen character named Te Ka.', 'Character'),
    ('119', 'Cards/191', 'Peter Pan', 3, false, '{ Storyborn, Hero }', 'Ruby', '{Rush}', 'Character'),
    ('126', 'Cards/192', 'Te Ka', 6, false, '{ Storyborn, Villain, Deity }', 'Ruby', 'Reckless', 'Character'),
    ('143', 'Cards/193', 'Chief Tui', 7, true, '{ Storyborn, Mentor, King }', 'Sapphire', '{Support}', 'Character'),
    ('147', 'Cards/194', 'Hades', 7, false, '{ Dreamborn, Villain, Deity }', 'Sapphire', 'Is there a Downside?: When you play this character, you may put chosen opposing character into their player''s inkwell facedown.', 'Character'),
    ('156', 'Cards/195', 'Philoctetes', 2, true, '{ Storyborn, Mentor }', 'Sapphire', '{Support}', 'Character'),
    ('159', 'Cards/196', 'Tamatoa', 8, true, '{ Storyborn, Villain }', 'Sapphire', 'What do we have here?: When you play this character and whenever he quests, you may return an item card from your discard to your hand. / Glam: This character gets +1 {lore} for each item you have in play.', 'Character'),
    ('167', 'Cards/197', 'Eye Of The Fates', 4, true, '{ Item }', 'Sapphire', 'See the Future: [{Exert}] - Chosen character gets +1 {lore} this turn.', 'Item'),
    ('168', 'Cards/198', 'Fishbone Quill', 3, true, '{ Item }', 'Sapphire', 'Go ahead and sign: [{Exert}] - Put any card from your hand into your inkwell facedown.', 'Item'),
    ('177', 'Cards/199', 'Donald Duck', 4, true, '{ Dreamborn, Hero, Musketeer }', 'Steel', '{Bodyguard} / Stay Alert!: During your turn, your Musketeer characters gain {Evasive}.', 'Character'),
    ('171', 'Cards/200', 'Aladdin', 2, true, '{ Storyborn, Hero }', 'Steel', '', 'Character'),
    ('184', 'Cards/201', 'Lilo', 3, true, '{ Storyborn, Hero }', 'Steel', '', 'Character'),
    ('204', 'Cards/202', 'Plasma Blaster', 3, false, '{ Item }', 'Steel', 'Quick Shot: [{Exert}, 2 {ink}] - Deal 1 damageto chosen character.', 'Item'),
    ('191', 'Cards/203', 'Starkey', 5, true, '{ Storyborn, Ally, Pirate }', 'Steel', 'Aye Aye, Captain: While you have a Captain character in play, this character gets +1 {lore}.', 'Character'),
    ('192', 'Cards/204', 'Te Ka', 6, true, '{ Dreamborn, Villain, Deity }', 'Steel', 'Seek the Heart: During your turn, whenever this character banishes another character in a challenge, you gain 2 lore.', 'Character');
EOSQL